#!/bin/sh

case "$1" in
  start)
        echo -n "Starting maia-httpd: "
        
        # Enable AD9361 RX fastlock pincontrol (ignore errors until device is ready)
        # Try a few times in case IIO enumerates a bit later.
        for i in 1 2 3 4 5; do
            /usr/bin/iio_attr -D ad9361-phy adi,rx-fastlock-pincontrol-enable 1 >/dev/null 2>&1 && break
            sleep 1
        done



        if [ -f /root/maia-httpd.xz ]; then
            xz -d /root/maia-httpd.xz
        fi
        cd /root
        start-stop-daemon -S -b -q -m -p /var/run/maia-httpd.pid -x /root/maia-httpd -- --ssl-cert /mnt/jffs2/maia-httpd.crt --ssl-key /mnt/jffs2/maia-httpd.key --ca-cert /mnt/jffs2/maia-sdr-ca.crt
        cd - > /dev/null
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
        echo -n "Stopping maia-httpd: "
        start-stop-daemon -K -q -p /var/run/maia-httpd.pid 2>/dev/null
        [ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
        $0 stop
        sleep 1
        $0 start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
